-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 27, 2023 at 05:25 AM
-- Server version: 10.4.27-MariaDB
-- PHP Version: 8.2.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `nutridieteshfa`
--

-- --------------------------------------------------------

--
-- Table structure for table `contact`
--

CREATE TABLE `contact` (
  `id` int(11) DEFAULT NULL,
  `sno` int(50) NOT NULL,
  `name` text NOT NULL,
  `email` varchar(50) NOT NULL,
  `phone_num` varchar(15) NOT NULL,
  `msg` text NOT NULL,
  `date` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `contact`
--

INSERT INTO `contact` (`id`, `sno`, `name`, `email`, `phone_num`, `msg`, `date`) VALUES
(NULL, 1, 'Fatima', 'fatima22@gmail.com', '0432146536', 'hey', '2023-01-08 00:00:00'),
(NULL, 20, 'fatima masood', 'bsef19m020@gmail.com', '03435762672', 'i wana generate diet plan', NULL),
(NULL, 21, 'fatima', 'fatima22@gmail.com', '0432657432', 'hey i wana generate a diet plan', NULL),
(NULL, 22, 'NutriDiet', 'saba@gmail.com', '098787575', 'njf', NULL),
(13, 30, 'Esha Tahir', 'eshatahir19@gmail.com', '0987777777', 'how are you', NULL);

-- --------------------------------------------------------

--
-- Table structure for table `diet_plan_model`
--

CREATE TABLE `diet_plan_model` (
  `plan_id` int(11) NOT NULL,
  `tdee` float NOT NULL,
  `id` int(11) NOT NULL,
  `breakfast_Monday` varchar(100) NOT NULL,
  `snack1_Monday` varchar(100) NOT NULL,
  `lunch_Monday` varchar(100) NOT NULL,
  `snack2_Monday` varchar(100) NOT NULL,
  `dinner_Monday` varchar(100) NOT NULL,
  `snack3_Monday` varchar(100) NOT NULL,
  `breakfast_Tuesday` varchar(100) NOT NULL,
  `snack1_Tuesday` varchar(100) NOT NULL,
  `lunch_Tuesday` varchar(100) NOT NULL,
  `snack2_Tuesday` varchar(100) NOT NULL,
  `dinner_Tuesday` varchar(100) NOT NULL,
  `snack3_Tuesday` varchar(100) NOT NULL,
  `breakfast_Wednesday` varchar(100) NOT NULL,
  `snack1_Wednesday` varchar(100) NOT NULL,
  `lunch_Wednesday` varchar(100) NOT NULL,
  `snack2_Wednesday` varchar(100) NOT NULL,
  `dinner_Wednesday` varchar(100) NOT NULL,
  `snack3_Wednesday` varchar(100) NOT NULL,
  `breakfast_Thursday` varchar(100) NOT NULL,
  `snack1_Thursday` varchar(100) NOT NULL,
  `lunch_Thursday` varchar(100) NOT NULL,
  `snack2_Thursday` varchar(100) NOT NULL,
  `dinner_Thursday` varchar(100) NOT NULL,
  `snack3_Thursday` varchar(100) NOT NULL,
  `breakfast_Friday` varchar(100) NOT NULL,
  `snack1_Friday` varchar(100) NOT NULL,
  `lunch_Friday` varchar(100) NOT NULL,
  `snack2_Friday` varchar(100) NOT NULL,
  `dinner_Friday` varchar(100) NOT NULL,
  `snack3_Friday` varchar(100) NOT NULL,
  `breakfast_Saturday` varchar(100) NOT NULL,
  `snack1_Saturday` varchar(100) NOT NULL,
  `lunch_Saturday` varchar(100) NOT NULL,
  `snack2_Saturday` varchar(100) NOT NULL,
  `dinner_Saturday` varchar(100) NOT NULL,
  `snack3_Saturday` varchar(100) NOT NULL,
  `breakfast_Sunday` varchar(100) NOT NULL,
  `snack1_Sunday` varchar(100) NOT NULL,
  `lunch_Sunday` varchar(100) NOT NULL,
  `snack2_Sunday` varchar(100) NOT NULL,
  `dinner_Sunday` varchar(100) NOT NULL,
  `snack3_Sunday` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `diet_plan_model`
--

INSERT INTO `diet_plan_model` (`plan_id`, `tdee`, `id`, `breakfast_Monday`, `snack1_Monday`, `lunch_Monday`, `snack2_Monday`, `dinner_Monday`, `snack3_Monday`, `breakfast_Tuesday`, `snack1_Tuesday`, `lunch_Tuesday`, `snack2_Tuesday`, `dinner_Tuesday`, `snack3_Tuesday`, `breakfast_Wednesday`, `snack1_Wednesday`, `lunch_Wednesday`, `snack2_Wednesday`, `dinner_Wednesday`, `snack3_Wednesday`, `breakfast_Thursday`, `snack1_Thursday`, `lunch_Thursday`, `snack2_Thursday`, `dinner_Thursday`, `snack3_Thursday`, `breakfast_Friday`, `snack1_Friday`, `lunch_Friday`, `snack2_Friday`, `dinner_Friday`, `snack3_Friday`, `breakfast_Saturday`, `snack1_Saturday`, `lunch_Saturday`, `snack2_Saturday`, `dinner_Saturday`, `snack3_Saturday`, `breakfast_Sunday`, `snack1_Sunday`, `lunch_Sunday`, `snack2_Sunday`, `dinner_Sunday`, `snack3_Sunday`) VALUES
(41, 2260.21, 13, 'soymilk( 83.3ml ), Orange, Whole Grain Bread(1 slice)', 'Flavored yogurt(125g)', 'soymilk( 83.3ml ), Leafy greens(Any Amount), Leafy greens, 1/4 medium avocado, 2 corn tortillas, Ban', 'Cottage cheese (125g), Any vegetable(80g)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Whole Grain Bread(1 slice), Small handful of nuts', 'Apple', 'Cooked fish(100g), Orange, Oats(250g)', 'Low fat milk(250ml)', 'soymilk( 83.3ml ), Any vegetable(80g), Leafy greens, 2 TSP (10 ml) olive oil, Half Large Potato(75g)', 'Soy nuts(30g), Any vegetable(80g)', 'Yogurt(1 cup), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 1/2 ounce  grated Parmesan ch', 'Orange', 'soymilk( 83.3ml ), Berries(80g), Cooked Grain(150g)', 'Low fat milk(250ml)', 'Yogurt(1 cup), Leafy greens(Any Amount), Leafy greens, 1/2 ounce  grated Parmesan cheese, Half Large', 'Soy nuts(30g), Any vegetable(80g)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Whole Grain Bread(1 slice), 2 TBSP (30g) reduced-', 'Apple', '', '', '', '', '', '', 'soymilk( 83.3ml ), Orange, Half Large Potato(75g)', 'Low fat milk(250ml)', 'soymilk( 83.3ml ), Any vegetable(80g), Leafy greens, 1/4 medium avocado, Oats(250g), Apple, Yogurt(1', 'Soy nuts(30g), Leafy greens(Any Amount)', 'Yogurt(1 cup), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, 2 TBSP (30g) reduced-calorie salad ', 'Banana', 'Cooked meat(85g), Dried Fruit(Handfull), Half Large Potato(75g)', 'Soy nuts(30g)', 'Cooked meat(85g), Any vegetable(80g), Leafy greens, 1/4 medium avocado, Cooked Grain(150g), Banana, ', 'Flavored yogurt(125g), Leafy greens(Any Amount)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Whole Grain Bread(1 slice), 1 TBSP (20g) jam, jel', 'Berries(80g)', 'Cooked fish(100g), Apple, Oats(250g)', 'boiled chick peas with squeezed lemon( 60g)', 'soymilk( 83.3ml ), Any vegetable(80g), Leafy greens, 2 TBSP (30g) reduced-calorie salad dressin, Coo', 'Cottage cheese (125g), Leafy greens(Any Amount)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, 1 TBSP (20g) jam, jelly, honey,', 'Dried Fruit(Handfull)'),
(42, 2260.21, 13, 'Yogurt(1 cup), Berries(80g), 2 corn tortillas', 'boiled chick peas with squeezed lemon( 60g)', 'Cooked fish(100g), Any vegetable(80g), Leafy greens, 2 TBSP (30g) reduced-calorie salad dressin, Who', 'Soy nuts(30g), Any vegetable(80g)', '1 whole egg + 4 egg whites, 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 2 TBSP (30g) red', 'Dried Fruit(Handfull)', 'soymilk( 83.3ml ), Apple, 2 corn tortillas', 'Cottage cheese (125g)', '1 whole egg + 4 egg whites, Leafy greens(Any Amount), Leafy greens, 1/2 ounce  grated Parmesan chees', 'Soy nuts(30g), Any vegetable(80g)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Whole Grain Bread(1 slice), Small handful of nuts', 'Banana', 'soymilk( 83.3ml ), Orange, Whole Grain Bread(1 slice)', 'Soy nuts(30g)', 'Yogurt(1 cup), Leafy greens(Any Amount), Leafy greens, 2 TBSP (30g) reduced-calorie salad dressin, H', 'Cottage cheese (125g), Leafy greens(Any Amount)', 'Cooked meat(85g), 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), 1 TBSP (20g) jam, jelly, honey', 'Banana', 'Yogurt(1 cup), Berries(80g), 2 corn tortillas', 'Soy nuts(30g)', 'soymilk( 83.3ml ), Leafy greens(Any Amount), Leafy greens, 2 TBSP (30g) reduced-calorie salad dressi', 'Flavored yogurt(125g), Leafy greens(Any Amount)', 'Yogurt(1 cup), 2 vegetables 80g, Leafy Greens, Oats(250g), 1 TBSP (20g) jam, jelly, honey, syrup, su', 'Orange', 'Yogurt(1 cup), Fruit Juice(125ml), Oats(250g)', 'boiled chick peas with squeezed lemon( 60g)', 'Yogurt(1 cup), Any vegetable(80g), Leafy greens, 1/4 medium avocado, Whole Grain Bread(1 slice), Ban', 'boiled chick peas with squeezed lemon( 60g), Any vegetable(80g)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, Whole Grain Bread(1 slice), 2 TSP (10 ml) olive o', 'Orange', 'Cooked fish(100g), Berries(80g), 2 corn tortillas', 'boiled chick peas with squeezed lemon( 60g)', '1 whole egg + 4 egg whites, Leafy greens(Any Amount), Leafy greens, Small handful of nuts, Whole Gra', 'boiled chick peas with squeezed lemon( 60g), Any vegetable(80g)', 'Cooked meat(85g), 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), Small handful of nuts, Yogurt(', 'Orange', 'soymilk( 83.3ml ), Berries(80g), Cooked Grain(150g)', 'Soy nuts(30g)', 'Cooked meat(85g), Leafy greens(Any Amount), Leafy greens, 1 TBSP (20g) jam, jelly, honey, syrup, sug', 'Cottage cheese (125g), Leafy greens(Any Amount)', 'Cooked meat(85g), 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), 1/4 medium avocado, Yogurt(1 c', 'Dried Fruit(Handfull)'),
(43, 2260.21, 13, 'Yogurt(1 cup), Fruit Juice(125ml), Oats(250g)', 'boiled chick peas with squeezed lemon( 60g)', 'soymilk( 83.3ml ), Any vegetable(80g), Leafy greens, Small handful of nuts, Whole Grain Bread(1 slic', 'Soy nuts(30g), Leafy greens(Any Amount)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Whole Grain Bread(1 slice), 1 TBSP (20g) jam, jel', 'Berries(80g)', 'Cooked fish(100g), Dried Fruit(Handfull), 2 corn tortillas', 'Soy nuts(30g)', 'Cooked meat(85g), Any vegetable(80g), Leafy greens, 2 TBSP (30g) reduced-calorie salad dressin, 2 co', 'boiled chick peas with squeezed lemon( 60g), Any vegetable(80g)', 'Cooked meat(85g), 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), 2 TBSP (30g) reduced-calorie s', 'Dried Fruit(Handfull)', 'soymilk( 83.3ml ), Banana, Oats(250g)', 'Cottage cheese (125g)', 'soymilk( 83.3ml ), Any vegetable(80g), Leafy greens, Small handful of nuts, Whole Grain Bread(1 slic', 'boiled chick peas with squeezed lemon( 60g), Any vegetable(80g)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), 1/4 medium avocado, Cooked fi', 'Berries(80g)', 'Yogurt(1 cup), Berries(80g), Cooked Grain(150g)', 'Soy nuts(30g)', 'Yogurt(1 cup), Leafy greens(Any Amount), Leafy greens, Small handful of nuts, Cooked Grain(150g), Fr', 'boiled chick peas with squeezed lemon( 60g), Any vegetable(80g)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 1/2 ounce  grated Parmesa', 'Orange', 'Yogurt(1 cup), Apple, 2 corn tortillas', 'Flavored yogurt(125g)', '1 whole egg + 4 egg whites, Any vegetable(80g), Leafy greens, 1/2 ounce  grated Parmesan cheese, Hal', 'boiled chick peas with squeezed lemon( 60g), Leafy greens(Any Amount)', 'Yogurt(1 cup), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, 1/2 ounce  grated Parmesan cheese, ', 'Fruit Juice(125ml)', 'Cooked fish(100g), Apple, Cooked Grain(150g)', 'boiled chick peas with squeezed lemon( 60g)', 'Yogurt(1 cup), Leafy greens(Any Amount), Leafy greens, 1/4 medium avocado, 2 corn tortillas, Berries', 'Low fat milk(250ml), Any vegetable(80g)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, Oats(250g), 1/2 ounce  grated Parmesan cheese, Yo', 'Dried Fruit(Handfull)', '1 whole egg + 4 egg whites, Dried Fruit(Handfull), Whole Grain Bread(1 slice)', 'boiled chick peas with squeezed lemon( 60g)', 'soymilk( 83.3ml ), Leafy greens(Any Amount), Leafy greens, 1 TBSP (20g) jam, jelly, honey, syrup, su', 'boiled chick peas with squeezed lemon( 60g), Any vegetable(80g)', '1 whole egg + 4 egg whites, 2 vegetables 80g, Leafy Greens, 2 corn tortillas, 1 TBSP (20g) jam, jell', 'Apple'),
(44, 2260.21, 13, 'Cooked meat(85g), Dried Fruit(Handfull), Whole Grain Bread(1 slice)', 'Soy nuts(30g)', '1 whole egg + 4 egg whites, Any vegetable(80g), Leafy greens, 2 TBSP (30g) reduced-calorie salad dre', 'boiled chick peas with squeezed lemon( 60g), Leafy greens(Any Amount)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 2 TBSP (30g) reduced-calo', 'Dried Fruit(Handfull)', 'Yogurt(1 cup), Orange, Cooked Grain(150g)', 'Cottage cheese (125g)', 'Cooked meat(85g), Any vegetable(80g), Leafy greens, 1/2 ounce  grated Parmesan cheese, Oats(250g), F', 'Flavored yogurt(125g), Any vegetable(80g)', 'Yogurt(1 cup), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 1/2 ounce  grated Parmesan ch', 'Dried Fruit(Handfull)', 'Cooked fish(100g), Fruit Juice(125ml), Cooked Grain(150g)', 'boiled chick peas with squeezed lemon( 60g)', '1 whole egg + 4 egg whites, Any vegetable(80g), Leafy greens, 2 TSP (10 ml) olive oil, Cooked Grain(', 'Flavored yogurt(125g), Any vegetable(80g)', 'Yogurt(1 cup), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, Small handful of nuts, Cooked meat(', 'Dried Fruit(Handfull)', 'Yogurt(1 cup), Berries(80g), Whole Grain Bread(1 slice)', 'Flavored yogurt(125g)', 'Yogurt(1 cup), Leafy greens(Any Amount), Leafy greens, 2 TBSP (30g) reduced-calorie salad dressin, O', 'Cottage cheese (125g), Any vegetable(80g)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 1 TBSP (20g) jam, jelly, ', 'Banana', 'Cooked meat(85g), Orange, Whole Grain Bread(1 slice)', 'Low fat milk(250ml)', 'soymilk( 83.3ml ), Leafy greens(Any Amount), Leafy greens, 1/2 ounce  grated Parmesan cheese, Oats(2', 'boiled chick peas with squeezed lemon( 60g), Any vegetable(80g)', 'Cooked meat(85g), 2 vegetables 80g, Leafy Greens, Oats(250g), 1/4 medium avocado, Yogurt(1 cup), Coo', 'Banana', '1 whole egg + 4 egg whites, Berries(80g), 2 corn tortillas', 'Flavored yogurt(125g)', 'Cooked fish(100g), Leafy greens(Any Amount), Leafy greens, 2 TBSP (30g) reduced-calorie salad dressi', 'Low fat milk(250ml), Any vegetable(80g)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), 1/2 ounce  grated Parmesan ch', 'Apple', 'Cooked fish(100g), Fruit Juice(125ml), 2 corn tortillas', 'boiled chick peas with squeezed lemon( 60g)', 'Yogurt(1 cup), Any vegetable(80g), Leafy greens, 2 TBSP (30g) reduced-calorie salad dressin, Cooked ', 'Cottage cheese (125g), Leafy greens(Any Amount)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), Small handful of nuts, Co', 'Apple'),
(45, 2260.21, 13, 'Yogurt(1 cup), Berries(80g), Half Large Potato(75g)', 'Low fat milk(250ml)', 'Cooked fish(100g), Any vegetable(80g), Leafy greens, 1 TBSP (20g) jam, jelly, honey, syrup, sugar, O', 'Cottage cheese (125g), Any vegetable(80g)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Oats(250g), 2 TBSP (30g) reduced-calorie salad dr', 'Banana', 'Yogurt(1 cup), Fruit Juice(125ml), Half Large Potato(75g)', 'boiled chick peas with squeezed lemon( 60g)', 'Cooked meat(85g), Leafy greens(Any Amount), Leafy greens, 2 TSP (10 ml) olive oil, 2 corn tortillas,', 'Cottage cheese (125g), Any vegetable(80g)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Oats(250g), 1/4 medium avocado, Cooked meat(85g),', 'Banana', 'Cooked fish(100g), Apple, Cooked Grain(150g)', 'Soy nuts(30g)', 'Cooked fish(100g), Leafy greens(Any Amount), Leafy greens, 1/2 ounce  grated Parmesan cheese, Oats(2', 'Soy nuts(30g), Any vegetable(80g)', 'Cooked meat(85g), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, 1/4 medium avocado, Cooked fish(', 'Dried Fruit(Handfull)', 'soymilk( 83.3ml ), Banana, Cooked Grain(150g)', 'Cottage cheese (125g)', 'Cooked fish(100g), Leafy greens(Any Amount), Leafy greens, 2 TBSP (30g) reduced-calorie salad dressi', 'Cottage cheese (125g), Any vegetable(80g)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), 1 TBSP (20g) jam, jelly, hone', 'Fruit Juice(125ml)', 'soymilk( 83.3ml ), Berries(80g), 2 corn tortillas', 'Soy nuts(30g)', '1 whole egg + 4 egg whites, Leafy greens(Any Amount), Leafy greens, 1/2 ounce  grated Parmesan chees', 'boiled chick peas with squeezed lemon( 60g), Any vegetable(80g)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 1/4 medium avocado, Cooke', 'Apple', 'Cooked fish(100g), Fruit Juice(125ml), 2 corn tortillas', 'Cottage cheese (125g)', 'Cooked meat(85g), Leafy greens(Any Amount), Leafy greens, 1/4 medium avocado, Cooked Grain(150g), Ba', 'Low fat milk(250ml), Any vegetable(80g)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, Whole Grain Bread(1 slice), 1 TBSP (20g) jam, jel', 'Banana', 'Cooked meat(85g), Orange, Oats(250g)', 'Soy nuts(30g)', 'Cooked fish(100g), Any vegetable(80g), Leafy greens, Small handful of nuts, Oats(250g), Apple, Yogur', 'Cottage cheese (125g), Leafy greens(Any Amount)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, Small handful of nuts, 1 whole ', 'Berries(80g)'),
(46, 2260.21, 13, 'Cooked fish(100g), Fruit Juice(125ml), Oats(250g)', 'Cottage cheese (125g)', '1 whole egg + 4 egg whites, Any vegetable(80g), Leafy greens, 1/4 medium avocado, Whole Grain Bread(', 'boiled chick peas with squeezed lemon( 60g), Leafy greens(Any Amount)', 'Cooked meat(85g), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, 2 TBSP (30g) reduced-calorie sal', 'Apple', 'Cooked meat(85g), Dried Fruit(Handfull), Oats(250g)', 'boiled chick peas with squeezed lemon( 60g)', 'soymilk( 83.3ml ), Leafy greens(Any Amount), Leafy greens, 1/4 medium avocado, 2 corn tortillas, Dri', 'Cottage cheese (125g), Any vegetable(80g)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, 2 TBSP (30g) reduced-calorie sa', 'Banana', 'Yogurt(1 cup), Orange, Oats(250g)', 'Low fat milk(250ml)', 'soymilk( 83.3ml ), Any vegetable(80g), Leafy greens, Small handful of nuts, Half Large Potato(75g), ', 'boiled chick peas with squeezed lemon( 60g), Leafy greens(Any Amount)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, Oats(250g), 2 TSP (10 ml) olive oil, soymilk( 83.', 'Apple', '1 whole egg + 4 egg whites, Apple, Half Large Potato(75g)', 'Flavored yogurt(125g)', 'Yogurt(1 cup), Leafy greens(Any Amount), Leafy greens, Small handful of nuts, Cooked Grain(150g), Ba', 'boiled chick peas with squeezed lemon( 60g), Any vegetable(80g)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, Whole Grain Bread(1 slice), 1/2 ounce  grated Par', 'Apple', '1 whole egg + 4 egg whites, Banana, 2 corn tortillas', 'Low fat milk(250ml)', 'Cooked fish(100g), Any vegetable(80g), Leafy greens, 1/4 medium avocado, Half Large Potato(75g), Ber', 'Low fat milk(250ml), Any vegetable(80g)', 'Yogurt(1 cup), 2 vegetables 80g, Leafy Greens, Whole Grain Bread(1 slice), Small handful of nuts, 1 ', 'Apple', 'Yogurt(1 cup), Dried Fruit(Handfull), Cooked Grain(150g)', 'Cottage cheese (125g)', 'Yogurt(1 cup), Any vegetable(80g), Leafy greens, 2 TSP (10 ml) olive oil, Oats(250g), Berries(80g), ', 'boiled chick peas with squeezed lemon( 60g), Any vegetable(80g)', 'Yogurt(1 cup), 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), 1 TBSP (20g) jam, jelly, honey, s', 'Fruit Juice(125ml)', 'Yogurt(1 cup), Fruit Juice(125ml), Half Large Potato(75g)', 'Low fat milk(250ml)', 'Yogurt(1 cup), Any vegetable(80g), Leafy greens, 2 TBSP (30g) reduced-calorie salad dressin, 2 corn ', 'Soy nuts(30g), Any vegetable(80g)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 1 TBSP (20g) jam, jelly, ', 'Dried Fruit(Handfull)'),
(47, 2260.21, 13, 'Cooked fish(100g), Dried Fruit(Handfull), Whole Grain Bread(1 slice)', 'Low fat milk(250ml)', 'soymilk( 83.3ml ), Leafy greens(Any Amount), Leafy greens, Small handful of nuts, Whole Grain Bread(', 'Flavored yogurt(125g), Leafy greens(Any Amount)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, 2 TBSP (30g) reduced-calorie sa', 'Fruit Juice(125ml)', 'Cooked meat(85g), Orange, Cooked Grain(150g)', 'Cottage cheese (125g)', 'soymilk( 83.3ml ), Leafy greens(Any Amount), Leafy greens, 1/4 medium avocado, 2 corn tortillas, Ban', 'Flavored yogurt(125g), Any vegetable(80g)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, Whole Grain Bread(1 slice), 2 TSP (10 ml) olive o', 'Fruit Juice(125ml)', 'Cooked meat(85g), Fruit Juice(125ml), 2 corn tortillas', 'boiled chick peas with squeezed lemon( 60g)', 'Yogurt(1 cup), Leafy greens(Any Amount), Leafy greens, 1 TBSP (20g) jam, jelly, honey, syrup, sugar,', 'Low fat milk(250ml), Any vegetable(80g)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 2 TSP (10 ml) olive oil, ', 'Apple', 'soymilk( 83.3ml ), Banana, Cooked Grain(150g)', 'Soy nuts(30g)', '1 whole egg + 4 egg whites, Leafy greens(Any Amount), Leafy greens, 2 TSP (10 ml) olive oil, Cooked ', 'boiled chick peas with squeezed lemon( 60g), Leafy greens(Any Amount)', 'Yogurt(1 cup), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 2 TSP (10 ml) olive oil, Yogu', 'Banana', '1 whole egg + 4 egg whites, Banana, Half Large Potato(75g)', 'Cottage cheese (125g)', '1 whole egg + 4 egg whites, Leafy greens(Any Amount), Leafy greens, 2 TBSP (30g) reduced-calorie sal', 'boiled chick peas with squeezed lemon( 60g), Any vegetable(80g)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, Whole Grain Bread(1 slice), Small handful of nuts', 'Apple', '1 whole egg + 4 egg whites, Dried Fruit(Handfull), Whole Grain Bread(1 slice)', 'Soy nuts(30g)', 'soymilk( 83.3ml ), Any vegetable(80g), Leafy greens, 1 TBSP (20g) jam, jelly, honey, syrup, sugar, C', 'Flavored yogurt(125g), Any vegetable(80g)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 2 TBSP (30g) reduced-calo', 'Banana', 'Yogurt(1 cup), Dried Fruit(Handfull), Half Large Potato(75g)', 'boiled chick peas with squeezed lemon( 60g)', 'Yogurt(1 cup), Any vegetable(80g), Leafy greens, Small handful of nuts, 2 corn tortillas, Fruit Juic', 'Low fat milk(250ml), Any vegetable(80g)', '1 whole egg + 4 egg whites, 2 vegetables 80g, Leafy Greens, Oats(250g), 1/2 ounce  grated Parmesan c', 'Fruit Juice(125ml)'),
(48, 2260.21, 13, '1 whole egg + 4 egg whites, Fruit Juice(125ml), 2 corn tortillas', 'boiled chick peas with squeezed lemon( 60g)', 'soymilk( 83.3ml ), Leafy greens(Any Amount), Leafy greens, Small handful of nuts, Cooked Grain(150g)', 'Flavored yogurt(125g), Any vegetable(80g)', 'Yogurt(1 cup), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, 2 TBSP (30g) reduced-calorie salad ', 'Berries(80g)', '1 whole egg + 4 egg whites, Berries(80g), Oats(250g)', 'Flavored yogurt(125g)', 'Cooked fish(100g), Any vegetable(80g), Leafy greens, 1 TBSP (20g) jam, jelly, honey, syrup, sugar, 2', 'boiled chick peas with squeezed lemon( 60g), Any vegetable(80g)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Oats(250g), 1/2 ounce  grated Parmesan cheese, Yo', 'Berries(80g)', 'Yogurt(1 cup), Dried Fruit(Handfull), 2 corn tortillas', 'Flavored yogurt(125g)', 'Cooked fish(100g), Any vegetable(80g), Leafy greens, 1/2 ounce  grated Parmesan cheese, Cooked Grain', 'boiled chick peas with squeezed lemon( 60g), Leafy greens(Any Amount)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), 1/2 ounce  grated Parmesan ch', 'Apple', '1 whole egg + 4 egg whites, Banana, Half Large Potato(75g)', 'Flavored yogurt(125g)', '1 whole egg + 4 egg whites, Any vegetable(80g), Leafy greens, 2 TSP (10 ml) olive oil, Whole Grain B', 'Flavored yogurt(125g), Leafy greens(Any Amount)', '1 whole egg + 4 egg whites, 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 1 TBSP (20g) jam', 'Fruit Juice(125ml)', 'Yogurt(1 cup), Dried Fruit(Handfull), Whole Grain Bread(1 slice)', 'Cottage cheese (125g)', '1 whole egg + 4 egg whites, Leafy greens(Any Amount), Leafy greens, 1/2 ounce  grated Parmesan chees', 'Cottage cheese (125g), Leafy greens(Any Amount)', '1 whole egg + 4 egg whites, 2 vegetables 80g, Leafy Greens, Oats(250g), 2 TBSP (30g) reduced-calorie', 'Apple', 'soymilk( 83.3ml ), Orange, Whole Grain Bread(1 slice)', 'Low fat milk(250ml)', 'Cooked meat(85g), Leafy greens(Any Amount), Leafy greens, 2 TSP (10 ml) olive oil, Cooked Grain(150g', 'Soy nuts(30g), Any vegetable(80g)', 'Yogurt(1 cup), 2 vegetables 80g, Leafy Greens, Whole Grain Bread(1 slice), 1/2 ounce  grated Parmesa', 'Berries(80g)', 'Yogurt(1 cup), Apple, Half Large Potato(75g)', 'Cottage cheese (125g)', '1 whole egg + 4 egg whites, Leafy greens(Any Amount), Leafy greens, 1/4 medium avocado, Oats(250g), ', 'Low fat milk(250ml), Leafy greens(Any Amount)', '1 whole egg + 4 egg whites, 2 vegetables 80g, Leafy Greens, Whole Grain Bread(1 slice), 1 TBSP (20g)', 'Berries(80g)'),
(49, 2260.21, 13, 'soymilk( 83.3ml ), Berries(80g), 2 corn tortillas', 'Low fat milk(250ml)', '1 whole egg + 4 egg whites, Any vegetable(80g), Leafy greens, 1 TBSP (20g) jam, jelly, honey, syrup,', 'Soy nuts(30g), Leafy greens(Any Amount)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 2 TSP (10 ml) olive oil, ', 'Apple', 'soymilk( 83.3ml ), Banana, Whole Grain Bread(1 slice)', 'Flavored yogurt(125g)', '1 whole egg + 4 egg whites, Any vegetable(80g), Leafy greens, 2 TBSP (30g) reduced-calorie salad dre', 'boiled chick peas with squeezed lemon( 60g), Leafy greens(Any Amount)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, 1/2 ounce  grated Parmesan chee', 'Berries(80g)', 'Yogurt(1 cup), Berries(80g), Oats(250g)', 'Soy nuts(30g)', '1 whole egg + 4 egg whites, Any vegetable(80g), Leafy greens, 1/4 medium avocado, Whole Grain Bread(', 'Cottage cheese (125g), Any vegetable(80g)', '1 whole egg + 4 egg whites, 2 vegetables 80g, Leafy Greens, Oats(250g), 1/4 medium avocado, Yogurt(1', 'Orange', 'Yogurt(1 cup), Dried Fruit(Handfull), Whole Grain Bread(1 slice)', 'boiled chick peas with squeezed lemon( 60g)', 'Cooked meat(85g), Any vegetable(80g), Leafy greens, Small handful of nuts, 2 corn tortillas, Berries', 'Cottage cheese (125g), Any vegetable(80g)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, Oats(250g), 1 TBSP (20g) jam, jelly, honey, syrup', 'Banana', 'Yogurt(1 cup), Banana, 2 corn tortillas', 'Flavored yogurt(125g)', '1 whole egg + 4 egg whites, Leafy greens(Any Amount), Leafy greens, 2 TSP (10 ml) olive oil, Whole G', 'Low fat milk(250ml), Any vegetable(80g)', 'Yogurt(1 cup), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 1/4 medium avocado, Cooked fi', 'Orange', 'Cooked meat(85g), Banana, Oats(250g)', 'Soy nuts(30g)', 'Yogurt(1 cup), Leafy greens(Any Amount), Leafy greens, 1/4 medium avocado, Oats(250g), Fruit Juice(1', 'boiled chick peas with squeezed lemon( 60g), Leafy greens(Any Amount)', 'Cooked meat(85g), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, Small handful of nuts, Yogurt(1 ', 'Apple', 'Cooked fish(100g), Fruit Juice(125ml), Half Large Potato(75g)', 'Cottage cheese (125g)', 'Yogurt(1 cup), Any vegetable(80g), Leafy greens, 1/2 ounce  grated Parmesan cheese, Whole Grain Brea', 'Soy nuts(30g), Leafy greens(Any Amount)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 1/4 medium avocado, Cooke', 'Fruit Juice(125ml)'),
(50, 2260.21, 13, '1 whole egg + 4 egg whites, Fruit Juice(125ml), Half Large Potato(75g)', 'Low fat milk(250ml)', 'Yogurt(1 cup), Any vegetable(80g), Leafy greens, 1/4 medium avocado, 2 corn tortillas, Fruit Juice(1', 'Cottage cheese (125g), Leafy greens(Any Amount)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 2 TBSP (30g) reduced-calo', 'Apple', 'soymilk( 83.3ml ), Orange, Half Large Potato(75g)', 'Low fat milk(250ml)', 'soymilk( 83.3ml ), Leafy greens(Any Amount), Leafy greens, Small handful of nuts, Oats(250g), Fruit ', 'Soy nuts(30g), Any vegetable(80g)', '1 whole egg + 4 egg whites, 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 1 TBSP (20g) jam', 'Apple', 'Cooked fish(100g), Banana, Whole Grain Bread(1 slice)', 'Soy nuts(30g)', 'Cooked fish(100g), Any vegetable(80g), Leafy greens, 1/4 medium avocado, 2 corn tortillas, Apple, so', 'Flavored yogurt(125g), Any vegetable(80g)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), Small handful of nuts, so', 'Dried Fruit(Handfull)', '1 whole egg + 4 egg whites, Banana, Whole Grain Bread(1 slice)', 'Soy nuts(30g)', 'Cooked meat(85g), Any vegetable(80g), Leafy greens, 1 TBSP (20g) jam, jelly, honey, syrup, sugar, Wh', 'Soy nuts(30g), Any vegetable(80g)', '1 whole egg + 4 egg whites, 2 vegetables 80g, Leafy Greens, 2 corn tortillas, 2 TBSP (30g) reduced-c', 'Dried Fruit(Handfull)', 'Cooked meat(85g), Dried Fruit(Handfull), Whole Grain Bread(1 slice)', 'Soy nuts(30g)', 'Cooked fish(100g), Leafy greens(Any Amount), Leafy greens, 1/4 medium avocado, Oats(250g), Orange, 1', 'Cottage cheese (125g), Leafy greens(Any Amount)', 'Cooked meat(85g), 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), Small handful of nuts, 1 whole', 'Orange', 'Cooked meat(85g), Dried Fruit(Handfull), Cooked Grain(150g)', 'Cottage cheese (125g)', 'Cooked meat(85g), Any vegetable(80g), Leafy greens, Small handful of nuts, Cooked Grain(150g), Apple', 'Low fat milk(250ml), Leafy greens(Any Amount)', 'Cooked meat(85g), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 1/4 medium avocado, Yogurt', 'Dried Fruit(Handfull)', 'Cooked meat(85g), Apple, 2 corn tortillas', 'Soy nuts(30g)', 'soymilk( 83.3ml ), Leafy greens(Any Amount), Leafy greens, Small handful of nuts, Oats(250g), Berrie', 'Soy nuts(30g), Any vegetable(80g)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, 2 TSP (10 ml) olive oil, 1 whol', 'Berries(80g)'),
(51, 2260.21, 13, 'Yogurt(1 cup), Apple, Oats(250g)', 'Flavored yogurt(125g)', 'Cooked fish(100g), Any vegetable(80g), Leafy greens, 1 TBSP (20g) jam, jelly, honey, syrup, sugar, H', 'Low fat milk(250ml), Leafy greens(Any Amount)', '1 whole egg + 4 egg whites, 2 vegetables 80g, Leafy Greens, Oats(250g), 2 TSP (10 ml) olive oil, 1 w', 'Fruit Juice(125ml)', 'Cooked meat(85g), Berries(80g), Whole Grain Bread(1 slice)', 'boiled chick peas with squeezed lemon( 60g)', 'Cooked fish(100g), Leafy greens(Any Amount), Leafy greens, 1 TBSP (20g) jam, jelly, honey, syrup, su', 'Soy nuts(30g), Any vegetable(80g)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Oats(250g), 1 TBSP (20g) jam, jelly, honey, syrup', 'Dried Fruit(Handfull)', 'Cooked fish(100g), Berries(80g), Half Large Potato(75g)', 'Soy nuts(30g)', 'Cooked fish(100g), Leafy greens(Any Amount), Leafy greens, Small handful of nuts, Whole Grain Bread(', 'Cottage cheese (125g), Any vegetable(80g)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, 1 TBSP (20g) jam, jelly, honey,', 'Berries(80g)', '1 whole egg + 4 egg whites, Dried Fruit(Handfull), Half Large Potato(75g)', 'Low fat milk(250ml)', 'Cooked meat(85g), Leafy greens(Any Amount), Leafy greens, Small handful of nuts, Oats(250g), Berries', 'Flavored yogurt(125g), Leafy greens(Any Amount)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, Small handful of nuts, Cooked m', 'Dried Fruit(Handfull)', 'Cooked meat(85g), Apple, Whole Grain Bread(1 slice)', 'Cottage cheese (125g)', 'Yogurt(1 cup), Any vegetable(80g), Leafy greens, 2 TSP (10 ml) olive oil, 2 corn tortillas, Apple, C', 'Cottage cheese (125g), Leafy greens(Any Amount)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), 2 TBSP (30g) reduced-calorie ', 'Fruit Juice(125ml)', 'soymilk( 83.3ml ), Apple, Whole Grain Bread(1 slice)', 'boiled chick peas with squeezed lemon( 60g)', 'soymilk( 83.3ml ), Any vegetable(80g), Leafy greens, 2 TSP (10 ml) olive oil, Oats(250g), Dried Frui', 'boiled chick peas with squeezed lemon( 60g), Leafy greens(Any Amount)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, 1/2 ounce  grated Parmesan chee', 'Apple', 'Cooked meat(85g), Berries(80g), 2 corn tortillas', 'Flavored yogurt(125g)', 'Cooked meat(85g), Leafy greens(Any Amount), Leafy greens, Small handful of nuts, Cooked Grain(150g),', 'Flavored yogurt(125g), Any vegetable(80g)', 'Cooked meat(85g), 2 vegetables 80g, Leafy Greens, Oats(250g), 2 TBSP (30g) reduced-calorie salad dre', 'Banana'),
(52, 2260.21, 13, 'Cooked meat(85g), Banana, Cooked Grain(150g)', 'Low fat milk(250ml)', 'Cooked fish(100g), Leafy greens(Any Amount), Leafy greens, 2 TBSP (30g) reduced-calorie salad dressi', 'Soy nuts(30g), Leafy greens(Any Amount)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), 1/4 medium avocado, Cooked me', 'Dried Fruit(Handfull)', 'Cooked meat(85g), Banana, 2 corn tortillas', 'Low fat milk(250ml)', 'Yogurt(1 cup), Leafy greens(Any Amount), Leafy greens, 2 TSP (10 ml) olive oil, Oats(250g), Orange, ', 'Flavored yogurt(125g), Any vegetable(80g)', 'Yogurt(1 cup), 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), 1/2 ounce  grated Parmesan cheese', 'Fruit Juice(125ml)', 'Cooked meat(85g), Orange, Oats(250g)', 'Low fat milk(250ml)', 'Yogurt(1 cup), Any vegetable(80g), Leafy greens, 2 TSP (10 ml) olive oil, Cooked Grain(150g), Orange', 'boiled chick peas with squeezed lemon( 60g), Leafy greens(Any Amount)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), Small handful of nuts, Co', 'Apple', 'Cooked meat(85g), Berries(80g), Half Large Potato(75g)', 'boiled chick peas with squeezed lemon( 60g)', 'Yogurt(1 cup), Any vegetable(80g), Leafy greens, 2 TSP (10 ml) olive oil, Half Large Potato(75g), Be', 'Soy nuts(30g), Any vegetable(80g)', 'Cooked meat(85g), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, 2 TBSP (30g) reduced-calorie sal', 'Apple', 'Yogurt(1 cup), Dried Fruit(Handfull), Half Large Potato(75g)', 'Flavored yogurt(125g)', 'Yogurt(1 cup), Leafy greens(Any Amount), Leafy greens, 1/2 ounce  grated Parmesan cheese, Oats(250g)', 'Low fat milk(250ml), Any vegetable(80g)', 'Cooked meat(85g), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, 1/2 ounce  grated Parmesan chees', 'Orange', '1 whole egg + 4 egg whites, Banana, Whole Grain Bread(1 slice)', 'Soy nuts(30g)', 'Yogurt(1 cup), Leafy greens(Any Amount), Leafy greens, 1 TBSP (20g) jam, jelly, honey, syrup, sugar,', 'Low fat milk(250ml), Leafy greens(Any Amount)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, Small handful of nuts, Cooked m', 'Berries(80g)', 'Cooked fish(100g), Fruit Juice(125ml), Whole Grain Bread(1 slice)', 'Soy nuts(30g)', 'Cooked fish(100g), Leafy greens(Any Amount), Leafy greens, 1/4 medium avocado, Oats(250g), Apple, Co', 'Soy nuts(30g), Any vegetable(80g)', 'Yogurt(1 cup), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, 1/2 ounce  grated Parmesan cheese, ', 'Fruit Juice(125ml)'),
(53, 2260.21, 13, 'Cooked fish(100g), Orange, 2 corn tortillas', 'Cottage cheese (125g)', 'Yogurt(1 cup), Leafy greens(Any Amount), Leafy greens, 2 TBSP (30g) reduced-calorie salad dressin, C', 'Flavored yogurt(125g), Leafy greens(Any Amount)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 1/4 medium avocado, soymi', 'Fruit Juice(125ml)', '1 whole egg + 4 egg whites, Dried Fruit(Handfull), Oats(250g)', 'Cottage cheese (125g)', 'soymilk( 83.3ml ), Any vegetable(80g), Leafy greens, 1/4 medium avocado, Whole Grain Bread(1 slice),', 'boiled chick peas with squeezed lemon( 60g), Any vegetable(80g)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, 1/2 ounce  grated Parmesan chee', 'Dried Fruit(Handfull)', 'Cooked meat(85g), Apple, Oats(250g)', 'Flavored yogurt(125g)', '1 whole egg + 4 egg whites, Leafy greens(Any Amount), Leafy greens, 2 TSP (10 ml) olive oil, Whole G', 'Cottage cheese (125g), Any vegetable(80g)', 'Yogurt(1 cup), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, 1 TBSP (20g) jam, jelly, honey, syr', 'Dried Fruit(Handfull)', 'soymilk( 83.3ml ), Apple, 2 corn tortillas', 'Flavored yogurt(125g)', 'soymilk( 83.3ml ), Any vegetable(80g), Leafy greens, 2 TSP (10 ml) olive oil, Whole Grain Bread(1 sl', 'Low fat milk(250ml), Leafy greens(Any Amount)', 'Cooked meat(85g), 2 vegetables 80g, Leafy Greens, Oats(250g), Small handful of nuts, Cooked meat(85g', 'Banana', 'Cooked meat(85g), Dried Fruit(Handfull), 2 corn tortillas', 'boiled chick peas with squeezed lemon( 60g)', 'soymilk( 83.3ml ), Any vegetable(80g), Leafy greens, 1/2 ounce  grated Parmesan cheese, Oats(250g), ', 'boiled chick peas with squeezed lemon( 60g), Any vegetable(80g)', '1 whole egg + 4 egg whites, 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 2 TSP (10 ml) ol', 'Banana', 'Cooked fish(100g), Apple, Half Large Potato(75g)', 'Cottage cheese (125g)', 'Cooked fish(100g), Leafy greens(Any Amount), Leafy greens, Small handful of nuts, Oats(250g), Orange', 'Low fat milk(250ml), Leafy greens(Any Amount)', 'Cooked meat(85g), 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), 1/2 ounce  grated Parmesan che', 'Orange', 'Cooked fish(100g), Apple, Oats(250g)', 'Soy nuts(30g)', 'soymilk( 83.3ml ), Any vegetable(80g), Leafy greens, 2 TBSP (30g) reduced-calorie salad dressin, 2 c', 'Low fat milk(250ml), Any vegetable(80g)', '1 whole egg + 4 egg whites, 2 vegetables 80g, Leafy Greens, Whole Grain Bread(1 slice), 2 TBSP (30g)', 'Banana'),
(54, 2260.21, 13, 'soymilk( 83.3ml ), Banana, Half Large Potato(75g)', 'Cottage cheese (125g)', 'Yogurt(1 cup), Leafy greens(Any Amount), Leafy greens, 1/4 medium avocado, Oats(250g), Orange, Yogur', 'boiled chick peas with squeezed lemon( 60g), Leafy greens(Any Amount)', '1 whole egg + 4 egg whites, 2 vegetables 80g, Leafy Greens, Whole Grain Bread(1 slice), 1/2 ounce  g', 'Apple', 'Yogurt(1 cup), Fruit Juice(125ml), Cooked Grain(150g)', 'Cottage cheese (125g)', 'Yogurt(1 cup), Leafy greens(Any Amount), Leafy greens, 2 TBSP (30g) reduced-calorie salad dressin, C', 'Low fat milk(250ml), Any vegetable(80g)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Oats(250g), Small handful of nuts, soymilk( 83.3m', 'Apple', 'Cooked fish(100g), Orange, Cooked Grain(150g)', 'Flavored yogurt(125g)', 'Cooked fish(100g), Leafy greens(Any Amount), Leafy greens, 1/4 medium avocado, Half Large Potato(75g', 'Cottage cheese (125g), Leafy greens(Any Amount)', 'Cooked meat(85g), 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), 1/4 medium avocado, 1 whole eg', 'Dried Fruit(Handfull)', 'Yogurt(1 cup), Orange, Oats(250g)', 'Cottage cheese (125g)', '1 whole egg + 4 egg whites, Leafy greens(Any Amount), Leafy greens, 1/4 medium avocado, Whole Grain ', 'Soy nuts(30g), Leafy greens(Any Amount)', 'Cooked meat(85g), 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), 1/4 medium avocado, soymilk( 8', 'Dried Fruit(Handfull)', 'Yogurt(1 cup), Orange, Oats(250g)', 'Flavored yogurt(125g)', 'soymilk( 83.3ml ), Any vegetable(80g), Leafy greens, 2 TBSP (30g) reduced-calorie salad dressin, Hal', 'Cottage cheese (125g), Any vegetable(80g)', 'Yogurt(1 cup), 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), 2 TBSP (30g) reduced-calorie sala', 'Apple', 'Cooked fish(100g), Fruit Juice(125ml), Oats(250g)', 'Cottage cheese (125g)', 'Cooked fish(100g), Leafy greens(Any Amount), Leafy greens, 2 TSP (10 ml) olive oil, Whole Grain Brea', 'Cottage cheese (125g), Leafy greens(Any Amount)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Whole Grain Bread(1 slice), 2 TBSP (30g) reduced-', 'Berries(80g)', '1 whole egg + 4 egg whites, Banana, 2 corn tortillas', 'Soy nuts(30g)', 'Yogurt(1 cup), Leafy greens(Any Amount), Leafy greens, 1/4 medium avocado, Whole Grain Bread(1 slice', 'Soy nuts(30g), Leafy greens(Any Amount)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Oats(250g), Small handful of nuts, Cooked meat(85', 'Berries(80g)'),
(55, 2260.21, 13, '1 whole egg + 4 egg whites, Fruit Juice(125ml), Half Large Potato(75g)', 'Cottage cheese (125g)', 'Cooked meat(85g), Any vegetable(80g), Leafy greens, Small handful of nuts, Cooked Grain(150g), Fruit', 'Low fat milk(250ml), Any vegetable(80g)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, 1/2 ounce  grated Parmesan chee', 'Berries(80g)', 'Cooked meat(85g), Banana, Cooked Grain(150g)', 'Soy nuts(30g)', 'Cooked fish(100g), Any vegetable(80g), Leafy greens, 1 TBSP (20g) jam, jelly, honey, syrup, sugar, 2', 'boiled chick peas with squeezed lemon( 60g), Any vegetable(80g)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, 2 TSP (10 ml) olive oil, Yogurt', 'Orange', '1 whole egg + 4 egg whites, Banana, Whole Grain Bread(1 slice)', 'boiled chick peas with squeezed lemon( 60g)', '1 whole egg + 4 egg whites, Any vegetable(80g), Leafy greens, 1/4 medium avocado, 2 corn tortillas, ', 'boiled chick peas with squeezed lemon( 60g), Any vegetable(80g)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 2 TBSP (30g) reduced-calo', 'Dried Fruit(Handfull)', '1 whole egg + 4 egg whites, Apple, 2 corn tortillas', 'Cottage cheese (125g)', 'Cooked meat(85g), Leafy greens(Any Amount), Leafy greens, 1/4 medium avocado, 2 corn tortillas, Berr', 'Soy nuts(30g), Leafy greens(Any Amount)', '1 whole egg + 4 egg whites, 2 vegetables 80g, Leafy Greens, Whole Grain Bread(1 slice), 1 TBSP (20g)', 'Dried Fruit(Handfull)', 'soymilk( 83.3ml ), Banana, Cooked Grain(150g)', 'Cottage cheese (125g)', 'Cooked fish(100g), Any vegetable(80g), Leafy greens, 1/4 medium avocado, Oats(250g), Banana, Cooked ', 'Cottage cheese (125g), Any vegetable(80g)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, Oats(250g), 1/4 medium avocado, Cooked meat(85g),', 'Dried Fruit(Handfull)', 'Cooked fish(100g), Banana, Whole Grain Bread(1 slice)', 'Low fat milk(250ml)', '1 whole egg + 4 egg whites, Any vegetable(80g), Leafy greens, Small handful of nuts, Cooked Grain(15', 'boiled chick peas with squeezed lemon( 60g), Any vegetable(80g)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), 1/4 medium avocado, soymilk( ', 'Fruit Juice(125ml)', 'Cooked fish(100g), Orange, Cooked Grain(150g)', 'Soy nuts(30g)', 'soymilk( 83.3ml ), Any vegetable(80g), Leafy greens, 2 TSP (10 ml) olive oil, Half Large Potato(75g)', 'Low fat milk(250ml), Any vegetable(80g)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 1 TBSP (20g) jam, jelly, ', 'Orange'),
(56, 2260.21, 13, 'Yogurt(1 cup), Berries(80g), Cooked Grain(150g)', 'Flavored yogurt(125g)', 'Cooked meat(85g), Leafy greens(Any Amount), Leafy greens, 2 TSP (10 ml) olive oil, Oats(250g), Berri', 'Cottage cheese (125g), Leafy greens(Any Amount)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Oats(250g), 2 TBSP (30g) reduced-calorie salad dr', 'Apple', 'Cooked fish(100g), Apple, Whole Grain Bread(1 slice)', 'Flavored yogurt(125g)', 'soymilk( 83.3ml ), Leafy greens(Any Amount), Leafy greens, Small handful of nuts, Cooked Grain(150g)', 'boiled chick peas with squeezed lemon( 60g), Leafy greens(Any Amount)', 'Cooked meat(85g), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 1 TBSP (20g) jam, jelly, h', 'Berries(80g)', 'Yogurt(1 cup), Berries(80g), Oats(250g)', 'boiled chick peas with squeezed lemon( 60g)', 'Cooked fish(100g), Leafy greens(Any Amount), Leafy greens, 1/4 medium avocado, Oats(250g), Dried Fru', 'Flavored yogurt(125g), Any vegetable(80g)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), 1/2 ounce  grated Parmesan ch', 'Banana', 'Yogurt(1 cup), Banana, Whole Grain Bread(1 slice)', 'Cottage cheese (125g)', 'soymilk( 83.3ml ), Leafy greens(Any Amount), Leafy greens, 2 TBSP (30g) reduced-calorie salad dressi', 'Cottage cheese (125g), Any vegetable(80g)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, Small handful of nuts, soymilk(', 'Fruit Juice(125ml)', '1 whole egg + 4 egg whites, Apple, Half Large Potato(75g)', 'Low fat milk(250ml)', 'Cooked fish(100g), Leafy greens(Any Amount), Leafy greens, Small handful of nuts, Half Large Potato(', 'Low fat milk(250ml), Any vegetable(80g)', '1 whole egg + 4 egg whites, 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 1/2 ounce  grate', 'Fruit Juice(125ml)', 'Cooked meat(85g), Berries(80g), Half Large Potato(75g)', 'Soy nuts(30g)', 'Cooked meat(85g), Leafy greens(Any Amount), Leafy greens, Small handful of nuts, Cooked Grain(150g),', 'Cottage cheese (125g), Any vegetable(80g)', '1 whole egg + 4 egg whites, 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), 1/2 ounce  grated Pa', 'Fruit Juice(125ml)', 'Yogurt(1 cup), Dried Fruit(Handfull), Whole Grain Bread(1 slice)', 'boiled chick peas with squeezed lemon( 60g)', 'Yogurt(1 cup), Leafy greens(Any Amount), Leafy greens, 1/4 medium avocado, Oats(250g), Dried Fruit(H', 'Low fat milk(250ml), Leafy greens(Any Amount)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), 1 TBSP (20g) jam, jelly, hone', 'Berries(80g)'),
(57, 2260.21, 13, 'Yogurt(1 cup), Banana, Oats(250g)', 'Cottage cheese (125g)', 'soymilk( 83.3ml ), Leafy greens(Any Amount), Leafy greens, 2 TBSP (30g) reduced-calorie salad dressi', 'Low fat milk(250ml), Leafy greens(Any Amount)', '1 whole egg + 4 egg whites, 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), 2 TSP (10 ml) olive ', 'Dried Fruit(Handfull)', 'Yogurt(1 cup), Apple, 2 corn tortillas', 'boiled chick peas with squeezed lemon( 60g)', 'Yogurt(1 cup), Any vegetable(80g), Leafy greens, 2 TBSP (30g) reduced-calorie salad dressin, Oats(25', 'boiled chick peas with squeezed lemon( 60g), Any vegetable(80g)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, Whole Grain Bread(1 slice), Small handful of nuts', 'Fruit Juice(125ml)', 'Cooked meat(85g), Berries(80g), Oats(250g)', 'Low fat milk(250ml)', 'Cooked fish(100g), Leafy greens(Any Amount), Leafy greens, 2 TSP (10 ml) olive oil, Half Large Potat', 'Cottage cheese (125g), Leafy greens(Any Amount)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Oats(250g), 1 TBSP (20g) jam, jelly, honey, syrup', 'Banana', '1 whole egg + 4 egg whites, Berries(80g), Half Large Potato(75g)', 'Flavored yogurt(125g)', 'Yogurt(1 cup), Any vegetable(80g), Leafy greens, 1/2 ounce  grated Parmesan cheese, 2 corn tortillas', 'Flavored yogurt(125g), Leafy greens(Any Amount)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), 2 TSP (10 ml) olive oil, Cook', 'Banana', 'Yogurt(1 cup), Apple, Oats(250g)', 'Flavored yogurt(125g)', 'Yogurt(1 cup), Leafy greens(Any Amount), Leafy greens, 1/4 medium avocado, Half Large Potato(75g), A', 'Low fat milk(250ml), Any vegetable(80g)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), Small handful of nuts, Yo', 'Dried Fruit(Handfull)', 'Cooked fish(100g), Dried Fruit(Handfull), Whole Grain Bread(1 slice)', 'Cottage cheese (125g)', 'Cooked fish(100g), Leafy greens(Any Amount), Leafy greens, 1/4 medium avocado, Half Large Potato(75g', 'Cottage cheese (125g), Leafy greens(Any Amount)', '1 whole egg + 4 egg whites, 2 vegetables 80g, Leafy Greens, Whole Grain Bread(1 slice), 1/2 ounce  g', 'Dried Fruit(Handfull)', 'Yogurt(1 cup), Banana, Whole Grain Bread(1 slice)', 'Flavored yogurt(125g)', 'Cooked meat(85g), Leafy greens(Any Amount), Leafy greens, 2 TSP (10 ml) olive oil, Cooked Grain(150g', 'Cottage cheese (125g), Any vegetable(80g)', 'Cooked meat(85g), 2 vegetables 80g, Leafy Greens, Oats(250g), 2 TBSP (30g) reduced-calorie salad dre', 'Orange'),
(58, 2260.21, 13, 'soymilk( 83.3ml ), Dried Fruit(Handfull), Cooked Grain(150g)', 'Low fat milk(250ml)', 'soymilk( 83.3ml ), Leafy greens(Any Amount), Leafy greens, 2 TSP (10 ml) olive oil, 2 corn tortillas', 'Flavored yogurt(125g), Any vegetable(80g)', '1 whole egg + 4 egg whites, 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 1 TBSP (20g) jam', 'Fruit Juice(125ml)', '1 whole egg + 4 egg whites, Banana, Cooked Grain(150g)', 'boiled chick peas with squeezed lemon( 60g)', '1 whole egg + 4 egg whites, Leafy greens(Any Amount), Leafy greens, 2 TSP (10 ml) olive oil, Cooked ', 'Soy nuts(30g), Leafy greens(Any Amount)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Whole Grain Bread(1 slice), 2 TBSP (30g) reduced-', 'Apple', 'Cooked meat(85g), Orange, 2 corn tortillas', 'Cottage cheese (125g)', '1 whole egg + 4 egg whites, Leafy greens(Any Amount), Leafy greens, 2 TBSP (30g) reduced-calorie sal', 'boiled chick peas with squeezed lemon( 60g), Leafy greens(Any Amount)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, 1 TBSP (20g) jam, jelly, honey,', 'Berries(80g)', 'soymilk( 83.3ml ), Banana, Cooked Grain(150g)', 'Soy nuts(30g)', '1 whole egg + 4 egg whites, Leafy greens(Any Amount), Leafy greens, Small handful of nuts, 2 corn to', 'Cottage cheese (125g), Any vegetable(80g)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 1/4 medium avocado, Cooke', 'Apple', 'Cooked meat(85g), Banana, Whole Grain Bread(1 slice)', 'Flavored yogurt(125g)', 'Yogurt(1 cup), Leafy greens(Any Amount), Leafy greens, 2 TBSP (30g) reduced-calorie salad dressin, 2', 'Low fat milk(250ml), Leafy greens(Any Amount)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, Whole Grain Bread(1 slice), 1/4 medium avocado, Y', 'Fruit Juice(125ml)', 'Cooked meat(85g), Berries(80g), 2 corn tortillas', 'boiled chick peas with squeezed lemon( 60g)', 'soymilk( 83.3ml ), Leafy greens(Any Amount), Leafy greens, 2 TSP (10 ml) olive oil, Oats(250g), Appl', 'Cottage cheese (125g), Leafy greens(Any Amount)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, Oats(250g), Small handful of nuts, Yogurt(1 cup),', 'Berries(80g)', 'Yogurt(1 cup), Dried Fruit(Handfull), Oats(250g)', 'Flavored yogurt(125g)', 'Cooked fish(100g), Any vegetable(80g), Leafy greens, 1/4 medium avocado, Cooked Grain(150g), Orange,', 'Soy nuts(30g), Any vegetable(80g)', 'Cooked meat(85g), 2 vegetables 80g, Leafy Greens, Oats(250g), Small handful of nuts, Yogurt(1 cup), ', 'Orange'),
(59, 2260.21, 13, 'Cooked fish(100g), Banana, Cooked Grain(150g)', 'Cottage cheese (125g)', 'Cooked fish(100g), Any vegetable(80g), Leafy greens, 2 TSP (10 ml) olive oil, Cooked Grain(150g), Dr', 'boiled chick peas with squeezed lemon( 60g), Any vegetable(80g)', 'Cooked meat(85g), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 1/4 medium avocado, soymil', 'Banana', 'Yogurt(1 cup), Berries(80g), 2 corn tortillas', 'boiled chick peas with squeezed lemon( 60g)', '1 whole egg + 4 egg whites, Any vegetable(80g), Leafy greens, Small handful of nuts, Whole Grain Bre', 'boiled chick peas with squeezed lemon( 60g), Any vegetable(80g)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), 1/2 ounce  grated Parmesan ch', 'Berries(80g)', 'Cooked fish(100g), Banana, Cooked Grain(150g)', 'boiled chick peas with squeezed lemon( 60g)', 'soymilk( 83.3ml ), Any vegetable(80g), Leafy greens, 2 TSP (10 ml) olive oil, Oats(250g), Banana, Co', 'Soy nuts(30g), Any vegetable(80g)', 'Cooked meat(85g), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 1 TBSP (20g) jam, jelly, h', 'Apple', 'Cooked meat(85g), Fruit Juice(125ml), Half Large Potato(75g)', 'boiled chick peas with squeezed lemon( 60g)', 'soymilk( 83.3ml ), Leafy greens(Any Amount), Leafy greens, 1 TBSP (20g) jam, jelly, honey, syrup, su', 'boiled chick peas with squeezed lemon( 60g), Any vegetable(80g)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Oats(250g), Small handful of nuts, Cooked meat(85', 'Apple', 'Yogurt(1 cup), Apple, 2 corn tortillas', 'Soy nuts(30g)', 'Cooked fish(100g), Leafy greens(Any Amount), Leafy greens, 2 TBSP (30g) reduced-calorie salad dressi', 'boiled chick peas with squeezed lemon( 60g), Leafy greens(Any Amount)', 'Cooked meat(85g), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 1/2 ounce  grated Parmesan', 'Dried Fruit(Handfull)', 'Cooked fish(100g), Banana, Cooked Grain(150g)', 'Low fat milk(250ml)', 'soymilk( 83.3ml ), Leafy greens(Any Amount), Leafy greens, 2 TSP (10 ml) olive oil, Cooked Grain(150', 'Flavored yogurt(125g), Leafy greens(Any Amount)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), 2 TSP (10 ml) olive oil, Cook', 'Apple', 'soymilk( 83.3ml ), Dried Fruit(Handfull), 2 corn tortillas', 'Low fat milk(250ml)', 'Yogurt(1 cup), Leafy greens(Any Amount), Leafy greens, 1/2 ounce  grated Parmesan cheese, Cooked Gra', 'Soy nuts(30g), Any vegetable(80g)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 2 TBSP (30g) reduced-calo', 'Dried Fruit(Handfull)');
INSERT INTO `diet_plan_model` (`plan_id`, `tdee`, `id`, `breakfast_Monday`, `snack1_Monday`, `lunch_Monday`, `snack2_Monday`, `dinner_Monday`, `snack3_Monday`, `breakfast_Tuesday`, `snack1_Tuesday`, `lunch_Tuesday`, `snack2_Tuesday`, `dinner_Tuesday`, `snack3_Tuesday`, `breakfast_Wednesday`, `snack1_Wednesday`, `lunch_Wednesday`, `snack2_Wednesday`, `dinner_Wednesday`, `snack3_Wednesday`, `breakfast_Thursday`, `snack1_Thursday`, `lunch_Thursday`, `snack2_Thursday`, `dinner_Thursday`, `snack3_Thursday`, `breakfast_Friday`, `snack1_Friday`, `lunch_Friday`, `snack2_Friday`, `dinner_Friday`, `snack3_Friday`, `breakfast_Saturday`, `snack1_Saturday`, `lunch_Saturday`, `snack2_Saturday`, `dinner_Saturday`, `snack3_Saturday`, `breakfast_Sunday`, `snack1_Sunday`, `lunch_Sunday`, `snack2_Sunday`, `dinner_Sunday`, `snack3_Sunday`) VALUES
(60, 2260.21, 13, 'Cooked meat(85g), Apple, 2 corn tortillas', 'Flavored yogurt(125g)', 'Cooked meat(85g), Any vegetable(80g), Leafy greens, 2 TBSP (30g) reduced-calorie salad dressin, 2 co', 'Soy nuts(30g), Leafy greens(Any Amount)', 'Yogurt(1 cup), 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), 2 TSP (10 ml) olive oil, soymilk(', 'Dried Fruit(Handfull)', 'Cooked fish(100g), Fruit Juice(125ml), Oats(250g)', 'boiled chick peas with squeezed lemon( 60g)', 'Yogurt(1 cup), Leafy greens(Any Amount), Leafy greens, 2 TBSP (30g) reduced-calorie salad dressin, 2', 'Soy nuts(30g), Any vegetable(80g)', 'soymilk( 83.3ml ), 2 vegetables 80g, Leafy Greens, 2 corn tortillas, 1 TBSP (20g) jam, jelly, honey,', 'Apple', 'Yogurt(1 cup), Banana, Cooked Grain(150g)', 'Low fat milk(250ml)', 'Cooked fish(100g), Any vegetable(80g), Leafy greens, Small handful of nuts, Whole Grain Bread(1 slic', 'Cottage cheese (125g), Leafy greens(Any Amount)', 'Cooked fish(100g), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), Small handful of nuts, so', 'Fruit Juice(125ml)', 'Yogurt(1 cup), Banana, Cooked Grain(150g)', 'Low fat milk(250ml)', 'soymilk( 83.3ml ), Any vegetable(80g), Leafy greens, Small handful of nuts, Cooked Grain(150g), Bana', 'Soy nuts(30g), Leafy greens(Any Amount)', 'Cooked meat(85g), 2 vegetables 80g, Leafy Greens, Oats(250g), 1/2 ounce  grated Parmesan cheese, 1 w', 'Apple', 'Yogurt(1 cup), Apple, Oats(250g)', 'boiled chick peas with squeezed lemon( 60g)', 'Cooked fish(100g), Any vegetable(80g), Leafy greens, 2 TSP (10 ml) olive oil, Oats(250g), Fruit Juic', 'Flavored yogurt(125g), Any vegetable(80g)', '1 whole egg + 4 egg whites, 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 1 TBSP (20g) jam', 'Orange', 'Cooked fish(100g), Fruit Juice(125ml), 2 corn tortillas', 'Soy nuts(30g)', 'Cooked fish(100g), Leafy greens(Any Amount), Leafy greens, 1 TBSP (20g) jam, jelly, honey, syrup, su', 'Flavored yogurt(125g), Leafy greens(Any Amount)', 'Yogurt(1 cup), 2 vegetables 80g, Leafy Greens, Cooked Grain(150g), 2 TSP (10 ml) olive oil, 1 whole ', 'Fruit Juice(125ml)', 'Cooked fish(100g), Berries(80g), Oats(250g)', 'boiled chick peas with squeezed lemon( 60g)', '1 whole egg + 4 egg whites, Leafy greens(Any Amount), Leafy greens, 2 TSP (10 ml) olive oil, Whole G', 'Cottage cheese (125g), Leafy greens(Any Amount)', 'Yogurt(1 cup), 2 vegetables 80g, Leafy Greens, Half Large Potato(75g), 2 TBSP (30g) reduced-calorie ', 'Orange');

-- --------------------------------------------------------

--
-- Table structure for table `user_info`
--

CREATE TABLE `user_info` (
  `info_id` int(11) NOT NULL,
  `name` varchar(50) NOT NULL,
  `age` int(11) NOT NULL,
  `gender` varchar(10) NOT NULL,
  `height` float NOT NULL,
  `weight` float NOT NULL,
  `phys_act` varchar(50) NOT NULL,
  `id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `user_info`
--

INSERT INTO `user_info` (`info_id`, `name`, `age`, `gender`, `height`, `weight`, `phys_act`, `id`) VALUES
(19, 'Esha Tahir', 22, 'Female', 173, 62, 'value3', 13),
(20, 'Esha Tahir', 22, 'Female', 173, 62, 'value3', 13),
(21, 'Esha Tahir', 22, 'Female', 173, 62, 'value3', 13),
(22, 'Esha Tahir', 22, 'Female', 170, 62, 'value3', 13),
(23, 'Esha Tahir', 22, 'Female', 173, 62, 'value3', 13),
(24, 'Esha Tahir', 22, 'Female', 170, 62, 'value3', 13),
(25, 'Esha Tahir', 22, 'Female', 170, 62, 'value3', 13),
(26, 'Iqra ', 21, 'Female', 162, 75, 'value4', 13),
(27, 'Esha Tahir', 22, 'Female', 173, 62, 'value3', 13),
(28, 'Esha Tahir', 22, 'Female', 173, 62, 'value3', 13),
(29, 'Esha Tahir', 22, 'Female', 173, 62, 'value3', 13),
(30, 'Esha Tahir', 22, 'Female', 173, 62, 'value3', 13),
(31, 'Esha Tahir', 22, 'Female', 173, 62, 'value3', 13),
(32, 'Esha Tahir', 22, 'Female', 173, 62, 'value3', 13),
(33, 'Esha Tahir', 22, 'Female', 173, 62, 'value3', 13),
(34, 'Esha Tahir', 22, 'Female', 173, 62, 'value3', 13),
(35, 'Esha Tahir', 22, 'Female', 173, 62, 'value3', 13);

-- --------------------------------------------------------

--
-- Table structure for table `user_login`
--

CREATE TABLE `user_login` (
  `id` int(11) NOT NULL,
  `email` varchar(50) NOT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `user_login`
--

INSERT INTO `user_login` (`id`, `email`, `username`, `password`) VALUES
(12, 'eshatahir19@gmail.com', 'esha19', 'esha@19'),
(13, 'esharajpoot2601@gmail.com', 'esha2601', 'esha@2601');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `contact`
--
ALTER TABLE `contact`
  ADD PRIMARY KEY (`sno`),
  ADD UNIQUE KEY `id` (`id`);

--
-- Indexes for table `diet_plan_model`
--
ALTER TABLE `diet_plan_model`
  ADD PRIMARY KEY (`plan_id`),
  ADD KEY `id` (`id`);

--
-- Indexes for table `user_info`
--
ALTER TABLE `user_info`
  ADD PRIMARY KEY (`info_id`),
  ADD KEY `fk_user_login_id` (`id`);

--
-- Indexes for table `user_login`
--
ALTER TABLE `user_login`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `contact`
--
ALTER TABLE `contact`
  MODIFY `sno` int(50) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=31;

--
-- AUTO_INCREMENT for table `diet_plan_model`
--
ALTER TABLE `diet_plan_model`
  MODIFY `plan_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=61;

--
-- AUTO_INCREMENT for table `user_info`
--
ALTER TABLE `user_info`
  MODIFY `info_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=36;

--
-- AUTO_INCREMENT for table `user_login`
--
ALTER TABLE `user_login`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `diet_plan_model`
--
ALTER TABLE `diet_plan_model`
  ADD CONSTRAINT `diet_plan_model_ibfk_1` FOREIGN KEY (`id`) REFERENCES `user_login` (`id`) ON DELETE CASCADE;

--
-- Constraints for table `user_info`
--
ALTER TABLE `user_info`
  ADD CONSTRAINT `fk_user_login_id` FOREIGN KEY (`id`) REFERENCES `user_login` (`id`) ON DELETE CASCADE,
  ADD CONSTRAINT `user_info_ibfk_1` FOREIGN KEY (`id`) REFERENCES `user_login` (`id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
